version: '3.5'

services:

  local-hermes-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: "hermes_db"
      POSTGRES_USER: "hermes_user"
      POSTGRES_PASSWORD: "hermes_password"
    ports:
      - "5442:5432"
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
    container_name: local-hermes-db
    networks:
      - hermes-shared-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: local-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - hermes-shared-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: local-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hermes-shared-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: local-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - hermes-shared-net

volumes:
  postgres-data-local:
    driver: local

networks:
  hermes-shared-net:
    name: hermes-shared-net